# Define your franchise lists for each CSV
yim_providers = [
    "Barnardos WRAP",
    "Bradford Youth Service",
    "Brathay",  # magic service type only to do
    "Inspired Neighbourhoods",  # todo check this one
    "Mind in Bradford",
    "Selfa",
]

other_vcse = [
    "All Star Youth Entertainment",
    "Bradford Counselling Service",
    "Bradford Bereavement Support",
    "Family Action Bradford",
    "Roshnighar",
    "STEP2 Young People&#039;s Health",  # check this one
    "The Cellar Trust",
]

bradford_filters = [
    
]

file_info = {
    "CYPMH_Clients_All": {
        "filename": "cypmh_clients_all",
        "columns": [
            'looked_after_child',
            'special_education_needs',
            'ehcp',
            'age',
            'gender_name',
            'ethnicity_name',

            ],
    },
    "CYPMH_Contacts_All": {
        "filename": "cypmh_contacts_all",
        "columns": [
            'looked_after_child',
            'special_education_needs',
            'ehcp',
            'contact_date',
            'contact_approach',
            'attendance'
        ],
    },
    "CYPMH_File_Closures_All": {
        "filename": "cypmh_file_closures_all",
        "columns": [
            'looked_after_child',
            'special_education_needs',
            'ehcp',
            'file_closure',
            'file_closure_reason'
        ],
    },
    "CYPMH_Goal_Themes_All": {
        "filename": "cypmh_goal_themes_all",
        "columns": [
            'looked_after_child',
            'special_education_needs',
            'ehcp',
            'goal_date',
            'goal_theme'
        ],
    },
    "CYPMH_Plans_And_Goals_All": {
        "filename": "cypmh_plans_and_goals_all",
        "columns": [
            'looked_after_child',
            'special_education_needs',
            'ehcp',
            'goal_date',
            'score_1',
            'score_2',
            'score_3',
            'initial_or_follow_up'
            
        ],
    },
    "CYPMH_Referral_Rejections_All": {
        "filename": "cypmh_referral_rejections_all",
        "columns": [
            'looked_after_child',
            'special_education_needs',
            'ehcp',
        ],
    },
    "CYPMH_Referrals": {
        "filename": "cypmh_referrals",
        "columns": [ 
        'looked_after_child',
            'special_education_needs',
            'ehcp',
            'referral_date',
            'global_id',
            'referral_source'
            
        ],
    },
    # "CYPMH_Referrals_MIB": {
    #     "filename": "cypmh_referrals_mib",
    #     "columns": [
    #         'looked_after_child',
    #         'special_education_needs',
    #         'ehcp',
    #     ],
    # },
    "CYPMH_Two_Contacts": {
        "filename": "cypmh_two_contacts",
        "columns": [
            'looked_after_child',
            'special_education_needs',
            'ehcp',
            'first_contact_/_indirect_date',
            'second_contact_/_indirect_date',
            'file_closures',
            'referral_rejections'
            # 'is_first_contact_/_indirect',
            # 'second_contact_/_indirect_date',
            # 'is_second_contact_/_indirect',
            # 'referral_date'
        ],
    },
    # "CYPMH_Two_Contacts_MIB": {
    #     "filename": "cypmh_two_contacts_mib",
    #     "columns": [
    #         'looked_after_child',
    #         'special_education_needs',
    #         'ehcp',
    #     ],
    # },
}

Overall_caseload_and_referrals = {
    "sheet_name": "Case_Status_Split",
    "table_name": "Overall_caseload_and_referrals",
    "row_names": [
        "Number referrals",
        "Number unique referrals",
        "Referrals accepted",
        "Referrals refused",
        "Number open cases",
        "Number closed cases",
    ],
    "placeholder_text": {"Number open cases": "PLACEHOLDER"},
    "row_db_logic": {
        "Number closed cases": "CYPMH_File_Closures_All",
    },
    "mib_row_db_default": "CYPMH_Referrals",
    "row_db_default": "CYPMH_Referrals",
}

CIC_CLA_caseload_and_referrals = {
    "sheet_name": "Case_Status_Split",
    "table_name": "CIC_CLA_caseload_and_referrals",
    "row_names": [
        "Number referrals",
        "Number unique referrals",
        "Referrals accepted",
        "Referrals refused",
        "Number open cases",
        "Number closed cases",
    ],
    "placeholder_text": {"Number open cases": "PLACEHOLDER"},
    "row_db_logic": {
        "Number closed cases": "CYPMH_File_Closures_All",
    },
    "mib_row_db_default": "CYPMH_Referrals",
    "row_db_default": "CYPMH_Referrals",
}

SEN_caseload_and_referrals = {
    "sheet_name": "Case_Status_Split",
    "table_name": "SEN_caseload_and_referrals",
    "row_names": [
        "Number referrals",
        "Number unique referrals",
        "Referrals accepted",
        "Referrals refused",
        "Number open cases",
        "Number closed cases",
    ],
    "placeholder_text": {"Number open cases": "PLACEHOLDER"},
    "row_db_logic": {
        "Number closed cases": "CYPMH_File_Closures_All",
    },
    "mib_row_db_default": "CYPMH_Referrals",
    "row_db_default": "CYPMH_Referrals",
}

EHCP_caseload_and_referrals = {
    "sheet_name": "Case_Status_Split",
    "table_name": "EHCP_caseload_and_referrals",
    "row_names": [
        "Number referrals",
        "Number unique referrals",
        "Referrals accepted",
        "Referrals refused",
        "Number open cases",
        "Number closed cases",
    ],
    "placeholder_text": {"Number open cases": "PLACEHOLDER"},
    "row_db_logic": {
        "Number closed cases": "CYPMH_File_Closures_All",
    },
    "mib_row_db_default": "CYPMH_Referrals",
    "row_db_default": "CYPMH_Referrals",
}

CRAVEN_caseload_and_referrals = {
    "sheet_name": "Case_Status_Split",
    "table_name": "CRAVEN_caseload_and_referrals",
    "row_names": [
        "Number referrals",
        "Number unique referrals",
        "Referrals accepted",
        "Referrals refused",
        "Number open cases",
        "Number closed cases",
    ],
    "placeholder_text": {"Number open cases": "PLACEHOLDER"},
    "row_db_logic": {
        "Number closed cases": "CYPMH_File_Closures_All",
    },
    "mib_row_db_default": "CYPMH_Referrals",
    "row_db_default": "CYPMH_Referrals",
}

BRADFORD_DISTRICT_caseload_and_referrals = {
    "sheet_name": "Case_Status_Split",
    "table_name": "BRADFORD_DISTRICT_caseload_and_referrals",
    "row_names": [
        "Number referrals",
        "Number unique referrals",
        "Referrals accepted",
        "Referrals refused",
        "Number open cases",
        "Number closed cases",
    ],
    "placeholder_text": {"Number open cases": "PLACEHOLDER"},
    "row_db_logic": {
        "Number closed cases": "CYPMH_File_Closures_All",
    },
    "mib_row_db_default": "CYPMH_Referrals",
    "row_db_default": "CYPMH_Referrals",
}


All_Referrals_by_demographics = {
    "sheet_name": "Demographic_split ",
    "table_name": "All_Referrals_by_demographics",
    "row_names": [
        "Age 4",
        "Age 5",
        "Age 6",
        "Age 7",
        "Age 8",
        "Age 9",
        "Age 10",
        "Age 11",
        "Age 12",
        "Age 13",
        "Age 14",
        "Age 15",
        "Age 16",
        "Age 17",
        "Age 18",
        "Age 19",
        "Age 20",
        "Age 21",
        "Age 22",
        "Age 23",
        "Age 24",
        "Age 25",
        "Out of age range (data input error)",
        "Female (including Transgender Woman)",
        "Male (including Transgender Man)",
        "Non-Binary",
        "Not known (Person stated Gender Code not recorded)",
        "No Stated (patient asked but declined to provide a response)",
        "Other (not listed)",
        "African",
        "Arab",
        "Bangladeshi",
        "Caribbean",
        "Central and Eastern European",
        "Chinese",
        "Gypsy/Roma/Traveller",
        "Indian",
        "Irish",
        "Latin America",
        "Pakistani",
        "White and Asian",
        "White and Black African",
        "White and Black Caribbean",
        "White British",
        "Any other Asian background",
        "Any other Black background",
        "Any other Ethnic group",
        "Any other Mixed background",
        "Any other White background",
        "Unknown Ethnicity",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Clients_All",
}


All_CIC_CLA_Referrals_by_demographics = {
    "sheet_name": "Demographic_split ",
    "table_name": "All_CIC_CLA_Referrals_by_demographics",
    "row_names": [
        "Age 4",
        "Age 5",
        "Age 6",
        "Age 7",
        "Age 8",
        "Age 9",
        "Age 10",
        "Age 11",
        "Age 12",
        "Age 13",
        "Age 14",
        "Age 15",
        "Age 16",
        "Age 17",
        "Age 18",
        "Age 19",
        "Age 20",
        "Age 21",
        "Age 22",
        "Age 23",
        "Age 24",
        "Age 25",
        "Out of age range (data input error)",
        "Female (including Transgender Woman)",
        "Male (including Transgender Man)",
        "Non-Binary",
        "Not known (Person stated Gender Code not recorded)",
        "No Stated (patient asked but declined to provide a response)",
        "Other (not listed)",
        "African",
        "Arab",
        "Bangladeshi",
        "Caribbean",
        "Central and Eastern European",
        "Chinese",
        "Gypsy/Roma/Traveller",
        "Indian",
        "Irish",
        "Latin America",
        "Pakistani",
        "White and Asian",
        "White and Black African",
        "White and Black Caribbean",
        "White British",
        "Any other Asian background",
        "Any other Black background",
        "Any other Ethnic group",
        "Any other Mixed background",
        "Any other White background",
        "Unknown Ethnicity",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Clients_All",
}

All_SEN_Referrals_by_demographics = {
    "sheet_name": "Demographic_split ",
    "table_name": "All_SEN_Referrals_by_demographics",
    "row_names": [
        "Age 4",
        "Age 5",
        "Age 6",
        "Age 7",
        "Age 8",
        "Age 9",
        "Age 10",
        "Age 11",
        "Age 12",
        "Age 13",
        "Age 14",
        "Age 15",
        "Age 16",
        "Age 17",
        "Age 18",
        "Age 19",
        "Age 20",
        "Age 21",
        "Age 22",
        "Age 23",
        "Age 24",
        "Age 25",
        "Out of age range (data input error)",
        "Female (including Transgender Woman)",
        "Male (including Transgender Man)",
        "Non-Binary",
        "Not known (Person stated Gender Code not recorded)",
        "No Stated (patient asked but declined to provide a response)",
        "Other (not listed)",
        "African",
        "Arab",
        "Bangladeshi",
        "Caribbean",
        "Central and Eastern European",
        "Chinese",
        "Gypsy/Roma/Traveller",
        "Indian",
        "Irish",
        "Latin America",
        "Pakistani",
        "White and Asian",
        "White and Black African",
        "White and Black Caribbean",
        "White British",
        "Any other Asian background",
        "Any other Black background",
        "Any other Ethnic group",
        "Any other Mixed background",
        "Any other White background",
        "Unknown Ethnicity",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Clients_All",
}

All_EHCP_Referrals_by_demographics = {
    "sheet_name": "Demographic_split ",
    "table_name": "All_EHCP_Referrals_by_demographics",
    "row_names": [
        "Age 4",
        "Age 5",
        "Age 6",
        "Age 7",
        "Age 8",
        "Age 9",
        "Age 10",
        "Age 11",
        "Age 12",
        "Age 13",
        "Age 14",
        "Age 15",
        "Age 16",
        "Age 17",
        "Age 18",
        "Age 19",
        "Age 20",
        "Age 21",
        "Age 22",
        "Age 23",
        "Age 24",
        "Age 25",
        "Out of age range (data input error)",
        "Female (including Transgender Woman)",
        "Male (including Transgender Man)",
        "Non-Binary",
        "Not known (Person stated Gender Code not recorded)",
        "No Stated (patient asked but declined to provide a response)",
        "Other (not listed)",
        "African",
        "Arab",
        "Bangladeshi",
        "Caribbean",
        "Central and Eastern European",
        "Chinese",
        "Gypsy/Roma/Traveller",
        "Indian",
        "Irish",
        "Latin America",
        "Pakistani",
        "White and Asian",
        "White and Black African",
        "White and Black Caribbean",
        "White British",
        "Any other Asian background",
        "Any other Black background",
        "Any other Ethnic group",
        "Any other Mixed background",
        "Any other White background",
        "Unknown Ethnicity",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Clients_All",
}

All_CRAVEN_Referrals_by_demographics = {
    "sheet_name": "Demographic_split ",
    "table_name": "All_CRAVEN_Referrals_by_demographics",
    "row_names": [
        "Age 4",
        "Age 5",
        "Age 6",
        "Age 7",
        "Age 8",
        "Age 9",
        "Age 10",
        "Age 11",
        "Age 12",
        "Age 13",
        "Age 14",
        "Age 15",
        "Age 16",
        "Age 17",
        "Age 18",
        "Age 19",
        "Age 20",
        "Age 21",
        "Age 22",
        "Age 23",
        "Age 24",
        "Age 25",
        "Out of age range (data input error)",
        "Female (including Transgender Woman)",
        "Male (including Transgender Man)",
        "Non-Binary",
        "Not known (Person stated Gender Code not recorded)",
        "No Stated (patient asked but declined to provide a response)",
        "Other (not listed)",
        "African",
        "Arab",
        "Bangladeshi",
        "Caribbean",
        "Central and Eastern European",
        "Chinese",
        "Gypsy/Roma/Traveller",
        "Indian",
        "Irish",
        "Latin America",
        "Pakistani",
        "White and Asian",
        "White and Black African",
        "White and Black Caribbean",
        "White British",
        "Any other Asian background",
        "Any other Black background",
        "Any other Ethnic group",
        "Any other Mixed background",
        "Any other White background",
        "Unknown Ethnicity",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Clients_All",
}

BRADFORD_DISTRICT_Referrals_by_demographics = {
    "sheet_name": "Demographic_split ",
    "table_name": "BRADFORD_DISTRICT_Referrals_by_demographics",
    "row_names": [
        "Age 4",
        "Age 5",
        "Age 6",
        "Age 7",
        "Age 8",
        "Age 9",
        "Age 10",
        "Age 11",
        "Age 12",
        "Age 13",
        "Age 14",
        "Age 15",
        "Age 16",
        "Age 17",
        "Age 18",
        "Age 19",
        "Age 20",
        "Age 21",
        "Age 22",
        "Age 23",
        "Age 24",
        "Age 25",
        "Out of age range (data input error)",
        "Female (including Transgender Woman)",
        "Male (including Transgender Man)",
        "Non-Binary",
        "Not known (Person stated Gender Code not recorded)",
        "No Stated (patient asked but declined to provide a response)",
        "Other (not listed)",
        "African",
        "Arab",
        "Bangladeshi",
        "Caribbean",
        "Central and Eastern European",
        "Chinese",
        "Gypsy/Roma/Traveller",
        "Indian",
        "Irish",
        "Latin America",
        "Pakistani",
        "White and Asian",
        "White and Black African",
        "White and Black Caribbean",
        "White British",
        "Any other Asian background",
        "Any other Black background",
        "Any other Ethnic group",
        "Any other Mixed background",
        "Any other White background",
        "Unknown Ethnicity",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Clients_All",
}


referrals_row_names = (
    [
        "Accident And Emergency Department",
        "CAMHS Crisis",
        "CAMHS Core/Step down",
        "CAMHS Waiting List",
        "Community-based Paediatrics",
        "Hospital-based Paediatrics",
        "School Nurse",
        "Other secondary care specialty",
        "Other service or agency",
        "Other Primary Health Care",
        "Internal Referral",
        "Youth Offending Service",
        "Police",
        "Housing Service",
        "Education Service",
        "Social Services",
        "Drug Action Team / Drug Misuse Agency",
        "Out of Area Agency",
        "GP services",
        "Self",
        "Carer",
        "Transfer by graduation from Child Adolescent Mental Health Services to Adult",
        "Voluntary Sector",
        "Unknown",
        "Single Point of Access Service",
    ],
)


Source_of_All_Referrals = {
    "sheet_name": "Referral_Source",
    "table_name": "Source_of_All_Referrals",
    "row_names": referrals_row_names[0],
    "placeholder_text": {},
    "mib_row_db_default": "CYPHM_",
    "row_db_default": "CYPMH_Referrals",
}

Source_of_Referrals___CIC_CLA = {
    "sheet_name": "Referral_Source",
    "table_name": "Source_of_Referrals_CIC_CLA",
    "row_names": referrals_row_names[0],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Referrals",
}

Source_of_Referrals___SEN = {
    "sheet_name": "Referral_Source",
    "table_name": "Source_of_Referrals_SEN",
    "row_names": referrals_row_names[0],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Referrals",
}

Source_of_Referrals___EHCP = {
    "sheet_name": "Referral_Source",
    "table_name": "Source_of_Referrals_EHCP",
    "row_names": referrals_row_names[0],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Referrals",
}

Source_of_Referrals___CRAVEN = {
    "sheet_name": "Referral_Source",
    "table_name": "Source_of_Referrals_CRAVEN",
    "row_names": referrals_row_names[0],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Referrals",
}

Source_of_Referrals___BRADFORD_DISTRICT = {
    "sheet_name": "Referral_Source",
    "table_name": "Source_of_Referrals_BRADFORD_DISTRICT",
    "row_names": referrals_row_names[0],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Referrals",
}


No__of_CYP_receiving_a_second_attended_contact_with_mental_health_services_ = {
    "sheet_name": "Two_attended_contacts_data",
    "table_name": "No_of_CYP_receiving_a_second_attended_contact_with_mental_health_services",
    "row_names": ["All", "CIC/CLA", "SEN", "EHCP", "CRAVEN", "BRADFORD DISTRICT"],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Two_Contacts",
    "row_db_default": "CYPMH_Two_Contacts",
}


DNAs_and_cancellations = {
    "sheet_name": "DNA",
    "table_name": "DNAs_and_cancellations",
    "row_names": [
        "All DNA Appointments",
        "All Cancelled by patient",
        "All Cancelled by Provider",
        "CIC/CLA DNA Appointments",
        "CIC/CLA Cancelled by patient",
        "CIC/CLA Cancelled by Provider",
        "SEN DNA Appointments",
        "SEN Cancelled by patient",
        "SEN Cancelled by Provider",
        "EHCP DNA Appointments",
        "EHCP Cancelled by patient",
        "EHCP Cancelled by Provider",
        "CRAVEN DNA Appointments",
        "CRAVEN Cancelled by patient",
        "CRAVEN Cancelled by Provider",
        "BRADFORD DISTRICT DNA Appointments",
        "BRADFORD DISTRICT Cancelled by patient",
        "BRADFORD DISTRICT Cancelled by Provider",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Contacts_All",
    "row_db_default": "CYPMH_Contacts_All",
}


Goals_Based_Outcomes = {
    "sheet_name": "Outcome_Data",
    "table_name": "Goals_Based_Outcomes",
    "row_names": [
        "Number All Initials completed",
        "Number All Follow ups completed",
        "Average Initial score",
        "Average Follow up score",
        "Number CIC/CLA Initials completed",
        "Number CIC/CLA Follow ups completed",
        "Average CIC/CLA Initial score",
        "Average CIC/CLA Follow up score",
        "Number SEN Initials completed",
        "Number SEN Follow ups completed",
        "Average SEN Initial score",
        "Average SEN Follow up score",
        "Number EHCP Initials completed",
        "Number EHCP Follow ups completed",
        "Average EHCP Initial score",
        "Average EHCP Follow up score",
        "Number CRAVEN Initials completed",
        "Number CRAVEN Follow ups completed",
        "Average CRAVEN Initial score",
        "Average CRAVEN Follow up score",
        "Number BRADFORD DISTRICT Initials completed",
        "Number BRADFORD DISTRICT Follow ups completed",
        "Average BRADFORD DISTRICT Initial score",
        "Average BRADFORD DISTRICT Follow up score",
    ],
    "placeholder_text": {
    },
    "mib_row_db_default": "CYPMH_Plans_And_Goals_All",
    "row_db_default": "CYPMH_Plans_And_Goals_All",
}


All_Goal_Themes = {
    "sheet_name": "Goal_Themes",
    "table_name": "All_Goal_Themes",
    "row_names": [
        "Being able to maintain and build positive relationships",
        "Being able to support others",
        "Being better at managing my emotional wellbeing",
        "Being better at managing risks and feeling safer",
        "Covid-19 Support",
        "Improving my confidence and self esteem",
        "Improving my physical wellbeing",
        "Reducing my isolation",
        "Understanding who I am",
        "TOTAL",
    ],
    "placeholder_text": {
    },
    "mib_row_db_default": "CYPMH_Goal_Themes_All",
    "row_db_default": "CYPMH_Goal_Themes_All",
}

CIC_Goal_Themes = {
    "sheet_name": "Goal_Themes",
    "table_name": "CIC_Goal_Themes",
    "row_names": [
        "Being able to maintain and build positive relationships",
        "Being able to support others",
        "Being better at managing my emotional wellbeing",
        "Being better at managing risks and feeling safer",
        "Covid-19 Support",
        "Improving my confidence and self esteem",
        "Improving my physical wellbeing",
        "Reducing my isolation",
        "Understanding who I am",
        "TOTAL",
    ],
    "placeholder_text": {
    },
    "mib_row_db_default": "CYPMH_Goal_Themes_All",
    "row_db_default": "CYPMH_Goal_Themes_All",
}

SEN_Goal_Themes = {
    "sheet_name": "Goal_Themes",
    "table_name": "SEN_Goal_Themes",
    "row_names": [
        "Being able to maintain and build positive relationships",
        "Being able to support others",
        "Being better at managing my emotional wellbeing",
        "Being better at managing risks and feeling safer",
        "Covid-19 Support",
        "Improving my confidence and self esteem",
        "Improving my physical wellbeing",
        "Reducing my isolation",
        "Understanding who I am",
        "TOTAL",
    ],
    "placeholder_text": {
    },
    "mib_row_db_default": "CYPMH_Goal_Themes_All",
    "row_db_default": "CYPMH_Goal_Themes_All",
}

EHCP_Goal_Themes = {
    "sheet_name": "Goal_Themes",
    "table_name": "EHCP_Goal_Themes",
    "row_names": [
        "Being able to maintain and build positive relationships",
        "Being able to support others",
        "Being better at managing my emotional wellbeing",
        "Being better at managing risks and feeling safer",
        "Covid-19 Support",
        "Improving my confidence and self esteem",
        "Improving my physical wellbeing",
        "Reducing my isolation",
        "Understanding who I am",
        "TOTAL",
    ],
    "placeholder_text": {
    },
    "mib_row_db_default": "CYPMH_Goal_Themes_All",
    "row_db_default": "CYPMH_Goal_Themes_All",
}

CRAVEN_Goal_Themes = {
    "sheet_name": "Goal_Themes",
    "table_name": "CRAVEN_Goal_Themes",
    "row_names": [
        "Being able to maintain and build positive relationships",
        "Being able to support others",
        "Being better at managing my emotional wellbeing",
        "Being better at managing risks and feeling safer",
        "Covid-19 Support",
        "Improving my confidence and self esteem",
        "Improving my physical wellbeing",
        "Reducing my isolation",
        "Understanding who I am",
        "TOTAL",
    ],
    "placeholder_text": {
    },
    "mib_row_db_default": "CYPMH_Goal_Themes_All",
    "row_db_default": "CYPMH_Goal_Themes_All",
}

Bradford_District_Goal_Themes = {
    "sheet_name": "Goal_Themes",
    "table_name": "Bradford_District_Goal_Themes",
    "row_names": [
        "Being able to maintain and build positive relationships",
        "Being able to support others",
        "Being better at managing my emotional wellbeing",
        "Being better at managing risks and feeling safer",
        "Covid-19 Support",
        "Improving my confidence and self esteem",
        "Improving my physical wellbeing",
        "Reducing my isolation",
        "Understanding who I am",
        "TOTAL",
    ],
    "placeholder_text": {
    },
    "mib_row_db_default": "CYPMH_Goal_Themes_All",
    "row_db_default": "CYPMH_Goal_Themes_All",
}


Overall_Discharges = {
    "sheet_name": "Discharge_Data",
    "table_name": "Overall_Discharges",
    "row_names": [
        "Number completed treatment",
        "Number inappropriate referrals",
        "Number who could not be contacted",
        "Number disengaged",
        "Number signposted to another CCG provider",
        "Not Disclosed",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_File_Closures_All",
    "row_db_default": "CYPMH_File_Closures_All",
}

Discharges_CIC_CLA = {
    "sheet_name": "Discharge_Data",
    "table_name": "Discharges_CIC_CLA",
    "row_names": [
        "Number completed treatment",
        "Number inappropriate referrals",
        "Number who could not be contacted",
        "Number disengaged",
        "Number signposted to another CCG provider",
        "Not Disclosed",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_File_Closures_All",
    "row_db_default": "CYPMH_File_Closures_All",
}

Discharges_SEN = {
    "sheet_name": "Discharge_Data",
    "table_name": "Discharges_SEN",
    "row_names": [
        "Number completed treatment",
        "Number inappropriate referrals",
        "Number who could not be contacted",
        "Number disengaged",
        "Number signposted to another CCG provider",
        "Not Disclosed",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_File_Closures_All",
    "row_db_default": "CYPMH_File_Closures_All",
}

Discharges_EHCP = {
    "sheet_name": "Discharge_Data",
    "table_name": "Discharges_EHCP",
    "row_names": [
        "Number completed treatment",
        "Number inappropriate referrals",
        "Number who could not be contacted",
        "Number disengaged",
        "Number signposted to another CCG provider",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_File_Closures_All",
    "row_db_default": "CYPMH_File_Closures_All",
}

Discharges_CRAVEN = {
    "sheet_name": "Discharge_Data",
    "table_name": "Discharges_CRAVEN",
    "row_names": [
        "Number completed treatment",
        "Number inappropriate referrals",
        "Number who could not be contacted",
        "Number disengaged",
        "Number signposted to another CCG provider",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_File_Closures_All",
    "row_db_default": "CYPMH_File_Closures_All",
}

Discharges_BRADFORD_DISTRICT = {
    "sheet_name": "Discharge_Data",
    "table_name": "Discharges_BRADFORD_DISTRICT",
    "row_names": [
        "Number completed treatment",
        "Number inappropriate referrals",
        "Number who could not be contacted",
        "Number disengaged",
        "Number signposted to another CCG provider",
        "Not Disclosed",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_File_Closures_All",
    "row_db_default": "CYPMH_File_Closures_All",
}


Overall_Number_on_Waiting_list = {
    "sheet_name": "Wait_List_Data",
    "table_name": "Overall_Number_on_Waiting_list",
    "row_names": ["All", "CIC/CLA", "SEN", "EHCP", "CRAVEN", "BRADFORD DISTRICT"],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Two_Contacts",
    "row_db_default": "CYPMH_Two_Contacts",
}


Overall_Wait_Times = {
    "sheet_name": "Wait_Times",
    "table_name": "Overall_Wait_Times",
    "row_names": [
        "Average Weeks from referral to 1st attended contact/indirect",
        "Average Weeks from referral to 2nd attended contact/indirect",
        "Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Two_Contacts",
    "row_db_default": "CYPMH_Two_Contacts",
}

CIC_CLA_Wait_Times = {
    "sheet_name": "Wait_Times",
    "table_name": "CIC_CLA_Wait_Times",
    "row_names": [
        "Average Weeks from referral to 1st attended contact/indirect",
        "Average Weeks from referral to 2nd attended contact/indirect",
        "Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Two_Contacts",
    "row_db_default": "CYPMH_Two_Contacts",
}

SEN_Wait_Times = {
    "sheet_name": "Wait_Times",
    "table_name": "SEN_Wait_Times",
    "row_names": [
        "Average Weeks from referral to 1st attended contact/indirect",
        "Average Weeks from referral to 2nd attended contact/indirect",
        "Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Two_Contacts",
    "row_db_default": "CYPMH_Two_Contacts",
}

EHCP_Wait_Times = {
    "sheet_name": "Wait_Times",
    "table_name": "EHCP_Wait_Times",
    "row_names": [
        "Average Weeks from referral to 1st attended contact/indirect",
        "Average Weeks from referral to 2nd attended contact/indirect",
        "Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Two_Contacts",
    "row_db_default": "CYPMH_Two_Contacts",
}

CRAVEN_Wait_Times = {
    "sheet_name": "Wait_Times",
    "table_name": "CRAVEN_Wait_Times",
    "row_names": [
        "Average Weeks from referral to 1st attended contact/indirect",
        "Average Weeks from referral to 2nd attended contact/indirect",
        "Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Two_Contacts",
    "row_db_default": "CYPMH_Two_Contacts",
}

BRADFORD_DISTRICT_Wait_Times = {
    "sheet_name": "Wait_Times",
    "table_name": "BRADFORD_DISTRICT_Wait_Times",
    "row_names": [
        "Average Weeks from referral to 1st attended contact/indirect",
        "Average Weeks from referral to 2nd attended contact/indirect",
        "Average Weeks between 1st Attended contact/Indirect & 2nd attended contact/indirect",
    ],
    "placeholder_text": {},
    "mib_row_db_default": "CYPMH_Two_Contacts",
    "row_db_default": "CYPMH_Two_Contacts",
}


Yim_Live = {
    "sheet_name": "YIM_LIVE_&_KCU_Delivery",
    "table_name": "Yim_Live",
    "row_names": ["Number Sessions", "Number Participants"],
    "placeholder_text": {
        "Number Sessions": "PLACEHOLDER",
        "Number Participants": "PLACEHOLDER",
    },
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Clients_All",
}

KCU = {
    "sheet_name": "YIM_LIVE_&_KCU_Delivery",
    "table_name": "KCU",
    "row_names": ["Number Schools/Youth Settings", "Number Participants"],
    "placeholder_text": {
        "Number Schools/Youth Settings": "PLACEHOLDER",
        "Number Participants": "PLACEHOLDER",
    },
    "mib_row_db_default": "CYPMH_Clients_All",
    "row_db_default": "CYPMH_Clients_All",
}


table_configs = [
    Overall_caseload_and_referrals,
    CIC_CLA_caseload_and_referrals,
    SEN_caseload_and_referrals,
    EHCP_caseload_and_referrals,
    CRAVEN_caseload_and_referrals,
    BRADFORD_DISTRICT_caseload_and_referrals,
    All_Referrals_by_demographics,
    All_CIC_CLA_Referrals_by_demographics,
    All_SEN_Referrals_by_demographics,
    All_EHCP_Referrals_by_demographics,
    All_CRAVEN_Referrals_by_demographics,
    BRADFORD_DISTRICT_Referrals_by_demographics,
    Source_of_All_Referrals,
    Source_of_Referrals___CIC_CLA,
    Source_of_Referrals___SEN,
    Source_of_Referrals___EHCP,
    Source_of_Referrals___CRAVEN,
    Source_of_Referrals___BRADFORD_DISTRICT,
    No__of_CYP_receiving_a_second_attended_contact_with_mental_health_services_,
    DNAs_and_cancellations,
    Goals_Based_Outcomes,
    All_Goal_Themes,
    CIC_Goal_Themes,
    SEN_Goal_Themes,
    EHCP_Goal_Themes,
    CRAVEN_Goal_Themes,
    Bradford_District_Goal_Themes,
    Overall_Discharges,
    Discharges_CIC_CLA,
    Discharges_SEN,
    Discharges_EHCP,
    Discharges_CRAVEN,
    Discharges_BRADFORD_DISTRICT,
    Overall_Number_on_Waiting_list,
    Overall_Wait_Times,
    CIC_CLA_Wait_Times,
    SEN_Wait_Times,
    EHCP_Wait_Times,
    CRAVEN_Wait_Times,
    BRADFORD_DISTRICT_Wait_Times,
    Yim_Live,
    KCU,
]

craven_postcodes = [
    "BD200AA",
    "BD200AB",
    "BD200AD",
    "BD200AE",
    "BD200AF",
    "BD200AG",
    "BD200AH",
    "BD200AJ",
    "BD200AL",
    "BD200AN",
    "BD200AP",
    "BD200AQ",
    "BD200AR",
    "BD200AS",
    "BD200AT",
    "BD200AU",
    "BD200AW",
    "BD200AX",
    "BD200AY",
    "BD200AZ",
    "BD200BA",
    "BD200BB",
    "BD200BD",
    "BD200BE",
    "BD200BG",
    "BD200BH",
    "BD200BJ",
    "BD200BL",
    "BD200BN",
    "BD200BP",
    "BD200BQ",
    "BD200BS",
    "BD200BT",
    "BD200BU",
    "BD200BW",
    "BD200BX",
    "BD200BY",
    "BD200BZ",
    "BD200DA",
    "BD200DB",
    "BD200DD",
    "BD200DE",
    "BD200DF",
    "BD200DG",
    "BD200DH",
    "BD200DJ",
    "BD200DL",
    "BD200DN",
    "BD200DP",
    "BD200DQ",
    "BD200DR",
    "BD200DS",
    "BD200DT",
    "BD200DU",
    "BD200DW",
    "BD200DX",
    "BD200DY",
    "BD200EA",
    "BD200EB",
    "BD200ED",
    "BD200EE",
    "BD200EF",
    "BD200EG",
    "BD200EH",
    "BD200EJ",
    "BD200EL",
    "BD200EN",
    "BD200EP",
    "BD200EQ",
    "BD200ER",
    "BD200ES",
    "BD200ET",
    "BD200EU",
    "BD200EW",
    "BD200EX",
    "BD200EY",
    "BD200EZ",
    "BD200FA",
    "BD200FB",
    "BD200FD",
    "BD200FE",
    "BD200FF",
    "BD200FJ",
    "BD200FN",
    "BD200FP",
    "BD200FQ",
    "BD200FR",
    "BD200FS",
    "BD200FU",
    "BD200HA",
    "BD200HB",
    "BD200HD",
    "BD200HE",
    "BD200HF",
    "BD200HG",
    "BD200HH",
    "BD200HJ",
    "BD200HL",
    "BD200HN",
    "BD200HP",
    "BD200HQ",
    "BD200HR",
    "BD200HS",
    "BD200HT",
    "BD200HU",
    "BD200HW",
    "BD200HX",
    "BD200HY",
    "BD200HZ",
    "BD200JA",
    "BD200JB",
    "BD200JD",
    "BD200JE",
    "BD200JF",
    "BD200JG",
    "BD200JH",
    "BD200JJ",
    "BD200JL",
    "BD200JN",
    "BD200JP",
    "BD200JQ",
    "BD200JR",
    "BD200JS",
    "BD200JT",
    "BD200JU",
    "BD200JW",
    "BD200JX",
    "BD200JY",
    "BD200JZ",
    "BD200LA",
    "BD200LB",
    "BD200LD",
    "BD200LE",
    "BD200LF",
    "BD200LG",
    "BD200LH",
    "BD200LJ",
    "BD200LL",
    "BD200LN",
    "BD200LP",
    "BD200LQ",
    "BD200LR",
    "BD200LS",
    "BD200LT",
    "BD200LU",
    "BD200LW",
    "BD200LX",
    "BD200LY",
    "BD200LZ",
    "BD200NA",
    "BD200NB",
    "BD200ND",
    "BD200NE",
    "BD200NF",
    "BD200NG",
    "BD200NH",
    "BD200NJ",
    "BD200NL",
    "BD200NN",
    "BD200NP",
    "BD200NQ",
    "BD200NR",
    "BD200NS",
    "BD200NT",
    "BD200NU",
    "BD200NW",
    "BD200NX",
    "BD200NY",
    "BD200NZ",
    "BD200PA",
    "BD200PB",
    "BD200PD",
    "BD200PE",
    "BD200PF",
    "BD200PG",
    "BD200PH",
    "BD200PJ",
    "BD200PL",
    "BD200PN",
    "BD200PP",
    "BD200PQ",
    "BD200PR",
    "BD200PS",
    "BD200PT",
    "BD200PU",
    "BD200PW",
    "BD200PX",
    "BD200QA",
    "BD200QB",
    "BD200QD",
    "BD200QE",
    "BD200QF",
    "BD200QG",
    "BD200QH",
    "BD200QJ",
    "BD200QL",
    "BD200QN",
    "BD200QP",
    "BD200QQ",
    "BD200QR",
    "BD200QS",
    "BD200QT",
    "BD200QU",
    "BD200QW",
    "BD200QX",
    "BD200QY",
    "BD200QZ",
    "BD200YH",
    "BD200YJ",
    "BD200YN",
    "BD200YP",
    "BD200YQ",
    "BD200YR",
    "BD200YS",
    "BD200YT",
    "BD200YU",
    "BD200YX",
    "BD200YZ",
    "BD205QN",
    "BD205RL",
    "BD206DH",
    "BD206FA",
    "BD206FB",
    "BD206FD",
    "BD206FE",
    "BD206FF",
    "BD206FG",
    "BD206FH",
    "BD206FJ",
    "BD206FL",
    "BD206FN",
    "BD206FP",
    "BD206FQ",
    "BD206FR",
    "BD206HH",
    "BD206LX",
    "BD206LY",
    "BD206NH",
    "BD206NJ",
    "BD206NN",
    "BD206NP",
    "BD206NR",
    "BD206NS",
    "BD206NT",
    "BD206NU",
    "BD206NX",
    "BD206PA",
    "BD206PB",
    "BD206PD",
    "BD206PE",
    "BD206PF",
    "BD206PG",
    "BD206PH",
    "BD206PJ",
    "BD206PL",
    "BD206PN",
    "BD206PP",
    "BD206PQ",
    "BD206PR",
    "BD206PS",
    "BD206PT",
    "BD206PU",
    "BD206PW",
    "BD206PX",
    "BD206PY",
    "BD206PZ",
    "BD206QA",
    "BD206QB",
    "BD206QD",
    "BD206QE",
    "BD206QF",
    "BD206QG",
    "BD206QH",
    "BD206QL",
    "BD206QN",
    "BD206QP",
    "BD206QQ",
    "BD206QR",
    "BD206QS",
    "BD206QT",
    "BD206QU",
    "BD206QW",
    "BD206QX",
    "BD206RA",
    "BD206RB",
    "BD206RD",
    "BD206RE",
    "BD206RF",
    "BD206RG",
    "BD206RH",
    "BD206RJ",
    "BD206RL",
    "BD206RN",
    "BD206RP",
    "BD206RQ",
    "BD206RR",
    "BD206RS",
    "BD206RT",
    "BD206RU",
    "BD206RW",
    "BD206RX",
    "BD206RY",
    "BD206RZ",
    "BD206SA",
    "BD206SB",
    "BD206SD",
    "BD206SE",
    "BD206SF",
    "BD206SG",
    "BD206SH",
    "BD206SJ",
    "BD206SL",
    "BD206SN",
    "BD206SP",
    "BD206SQ",
    "BD206SR",
    "BD206SS",
    "BD206ST",
    "BD206SU",
    "BD206SW",
    "BD206SX",
    "BD206SY",
    "BD206SZ",
    "BD206TA",
    "BD206TB",
    "BD206TD",
    "BD206TE",
    "BD206TF",
    "BD206TG",
    "BD206TH",
    "BD206TL",
    "BD206TN",
    "BD206TP",
    "BD206TQ",
    "BD206TR",
    "BD206TS",
    "BD206TT",
    "BD206TU",
    "BD206TW",
    "BD206TX",
    "BD206UN",
    "BD206UP",
    "BD206UW",
    "BD206XF",
    "BD206XG",
    "BD206XH",
    "BD206XJ",
    "BD206XR",
    "BD206XT",
    "BD206XW",
    "BD207AG",
    "BD207AH",
    "BD207AQ",
    "BD207SD",
    "BD207SJ",
    "BD207SL",
    "BD207SN",
    "BD207SP",
    "BD207SR",
    "BD207SS",
    "BD207ST",
    "BD207SU",
    "BD207SW",
    "BD207SX",
    "BD207SY",
    "BD207SZ",
    "BD207YY",
    "BD208AD",
    "BD208AF",
    "BD208AG",
    "BD208AZ",
    "BD208BA",
    "BD208BJ",
    "BD208BQ",
    "BD208BS",
    "BD208BW",
    "BD208BZ",
    "BD208DN",
    "BD208TY",
    "BD208TZ",
    "BD208UA",
    "BD208UB",
    "BD208UD",
    "BD208UE",
    "BD208UF",
    "BD208UG",
    "BD208UH",
    "BD208UJ",
    "BD208UL",
    "BD208UN",
    "BD208UP",
    "BD208UQ",
    "BD208UR",
    "BD208US",
    "BD208UT",
    "BD208UU",
    "BD208UW",
    "BD208UX",
    "BD208UY",
    "BD208UZ",
    "BD208YS",
    "BD208YU",
    "BD208YX",
    "BD208YZ",
    "BD209AA",
    "BD209BY",
    "BD209DA",
    "BD209FA",
    "BD209FB",
    "BD209HH",
    "BD209HJ",
    "BD209HN",
    "BD209HP",
    "BD209HR",
    "BD209HS",
    "BD209HU",
    "BD209HW",
    "BD209JA",
    "BD209JB",
    "BD209JD",
    "BD209JE",
    "BD209JF",
    "BD209JG",
    "BD209JH",
    "BD209JJ",
    "BD209JL",
    "BD209JN",
    "BD209JP",
    "BD209JQ",
    "BD209JR",
    "BD209JS",
    "BD209JT",
    "BD209JU",
    "BD209JX",
    "BD209JY",
    "BD209JZ",
    "BD209LA",
    "BD209LB",
    "BD209LD",
    "BD209LE",
    "BD209LF",
    "BD209LG",
    "BD209LH",
    "BD209LJ",
    "BD209LL",
    "BD209LN",
    "BD209LP",
    "BD209LQ",
    "BD209LR",
    "BD209LS",
    "BD209LT",
    "BD209LU",
    "BD209LW",
    "BD209LX",
    "BD209LY",
    "BD209LZ",
    "BD209NA",
    "BD209NB",
    "BD209ND",
    "BD209NE",
    "BD209NF",
    "BD209NG",
    "BD209NH",
    "BD209NJ",
    "BD209NL",
    "BD209NN",
    "BD209NP",
    "BD209NQ",
    "BD209NR",
    "BD209NS",
    "BD209NT",
    "BD209NU",
    "BD209NW",
    "BD209NX",
    "BD209NY",
    "BD209NZ",
    "BD209PA",
    "BD209PB",
    "BD209PD",
    "BD209PE",
    "BD209PF",
    "BD209PG",
    "BD209PH",
    "BD209PJ",
    "BD209PL",
    "BD209PN",
    "BD209PP",
    "BD209PQ",
    "BD209PR",
    "BD209PS",
    "BD209PT",
    "BD209PU",
    "BD209PW",
    "BD209PX",
    "BD209PY",
    "BD209PZ",
    "BD209QA",
    "BD209QE",
    "BD209QF",
    "BD209QP",
    "BD209QR",
    "BD209QS",
    "BD209QT",
    "BD209QZ",
    "BD209UX",
    "BD209UZ",
    "BD209YZ",
    "LS270TA",
    "LS270TH",
    "LS270XA",
    "LS270XE",
    "LS270XG",
    "LS270XJ",
    "LS270XQ",
    "LS270YB",
    "LS290BF",
    "LS290FA",
    "LS290FB",
    "LS290FD",
    "LS290FF",
    "LS290HA",
    "LS290HX",
    "LS290HY",
    "LS290HZ",
    "LS290JA",
    "LS290JB",
    "LS290JD",
    "LS290JE",
    "LS290JF",
    "LS290JG",
    "LS290JH",
    "LS290JJ",
    "LS290JL",
    "LS290JN",
    "LS290JP",
    "LS290JQ",
    "LS290JR",
    "LS290JS",
    "LS290JT",
    "LS290JW",
    "LS290JX",
    "LS290JY",
    "LS290JZ",
    "LS290LA",
    "LS290LB",
    "LS290LD",
    "LS290LE",
    "LS290LF",
    "LS290LG",
    "LS290LH",
    "LS290LJ",
    "LS290LL",
    "LS290LN",
    "LS290LP",
    "LS290LQ",
    "LS290LR",
    "LS290LS",
    "LS290LT",
    "LS290LU",
    "LS290LW",
    "LS290LX",
    "LS290LY",
    "LS290LZ",
    "LS290NA",
    "LS290NB",
    "LS290ND",
    "LS290NE",
    "LS290NF",
    "LS290NG",
    "LS290NH",
    "LS290NJ",
    "LS290NL",
    "LS290NN",
    "LS290NP",
    "LS290NQ",
    "LS290NR",
    "LS290NS",
    "LS290NT",
    "LS290NU",
    "LS290NW",
    "LS290NX",
    "LS290NY",
    "LS290NZ",
    "LS290PA",
    "LS290PB",
    "LS290PD",
    "LS290PE",
    "LS290PF",
    "LS290PG",
    "LS290PH",
    "LS290PJ",
    "LS290PL",
    "LS290PN",
    "LS290PP",
    "LS290PQ",
    "LS290PR",
    "LS290PS",
    "LS290PT",
    "LS290PU",
    "LS290PW",
    "LS290PX",
    "LS290PY",
    "LS290PZ",
    "LS290QA",
    "LS290QB",
    "LS290QD",
    "LS290QE",
    "LS290QF",
    "LS290QG",
    "LS290QH",
    "LS290QJ",
    "LS290QL",
    "LS290QN",
    "LS290QP",
    "LS290QQ",
    "LS290QR",
    "LS290QS",
    "LS290QT",
    "LS290QU",
    "LS290QW",
    "LS290QX",
    "LS290QY",
    "LS290QZ",
    "LS290RA",
    "LS290RB",
    "LS290RD",
    "LS290RE",
    "LS290RF",
    "LS290RG",
    "LS290RJ",
    "LS290RL",
    "LS290RN",
    "LS290RP",
    "LS290RQ",
    "LS290RR",
    "LS290RS",
    "LS290RT",
    "LS290RU",
    "LS290RW",
    "LS290RX",
    "LS290RY",
    "LS290RZ",
    "LS290SA",
    "LS290SB",
    "LS290SD",
    "LS290SE",
    "LS290SF",
    "LS290SH",
    "LS290SJ",
    "LS290SL",
    "LS290SP",
    "LS290SQ",
    "LS290SR",
    "LS290SS",
    "LS290ST",
    "LS290SU",
    "LS290SW",
    "LS290SY",
    "LS290SZ",
    "LS290TA",
    "LS290TB",
    "LS290TD",
    "LS290TE",
    "LS290TF",
    "LS290TG",
    "LS290TH",
    "LS290TJ",
    "LS290TL",
    "LS290TN",
    "LS290TP",
    "LS290TQ",
    "LS290TR",
    "LS290TS",
    "LS290TU",
    "LS290TW",
    "LS290TX",
    "LS290UA",
    "LS290UD",
    "LS290UE",
    "LS290WA",
    "LS290WR",
    "LS290XA",
    "LS290XB",
    "LS290XE",
    "LS290XF",
    "LS290XG",
    "LS290XH",
    "LS290XJ",
    "LS290XL",
    "LS290XP",
    "LS290XQ",
    "LS290XR",
    "LS290XU",
    "LS290XW",
    "LS290XY",
    "LS290XZ",
    "LS290YA",
    "LS290YB",
    "LS290YE",
    "LS290YJ",
    "LS299JU",
    "LS299JX",
    "LS299JY",
]
